# WhoisBot Demo Workflow
#
# This workflow provides a demonstration interface for WhoisBot:
# - Allows manual triggering with contact details input
# - Uses Node.js 20.17 runtime
# - Requires Bing and OpenAI API keys in repository secrets
#
# Usage:
# 1. Navigate to Actions tab
# 2. Select "Who is Bot" workflow
# 3. Click "Run workflow"
# 4. Enter contact details when prompted
#
# Required Secrets:
# - BING_API_KEY: API key for Bing Search
# - OPENAI_API_KEY: API key for Azure OpenAI

name: Who is Bot

on:
  workflow_dispatch:
    inputs:
      contactDetails:
        description: 'Contact details of the person'
        required: true

jobs:
  analyze_person:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build

      - name: Run Who is Bot
        run: node dist/index.js -c "${{ github.event.inputs.contactDetails }}"
        env:
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Output analysis
        run: echo "${{ steps.analyze_person.outputs.analysis }}"
